[package]
name        = "benches"
version     = "0.1.0"
edition     = "2021"
publish     = false

[dependencies]
ogurpchik = { path = "../" }
testschema = { path = "../tests/testschema" }

compio       = { version = "0.18.0", features = ["net", "io-compat", "macros", "time"] }
capnp        = "0.27"
futures      = "0.3"
futures-util = "0.3"
criterion    = { version = "0.8", features = ["html_reports"] }

[[bench]]
name    = "rpc_latency"
path    = "src/rpc_latency.rs"
harness = false

[[bench]]
name    = "bridge_cost"
path    = "src/bridge_cost.rs"
harness = false

[profile.release]
debug           = true
split-debuginfo = "packed"

[profile.bench]
inherits        = "release"
debug           = true
split-debuginfo = "packed"
lto             = "thin"
codegen-units   = 1
